spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hospitaldb
    username: postgres
    password: 312125
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
