spring:
  datasource:
    url: jdbc:postgresql://localhost/hospitaldb
    username: postgres
    password: 312125
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.PostgreSQL95Dialect