spring:
  datasource:
    url: jdbc:postgresql://localhost/hospitaldb
    username: postgres
    password: 312125
    driverClassName: org.postgresql.Driver
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
vaadin:
  urlMapping: /frontend/*
