GET http://localhost:8080/api/diagnosis/get/3
Accept: application/json
###
GET http://localhost:8080/api/people/get/10
Accept: application/json
###
GET http://localhost:8080/api/ward/get/6
Accept: application/json
###
POST http://localhost:8080/api/diagnosis/save
Content-Type: application/json

{
  "peopleList": [],
  "id": null,
  "name": "Sifilis"
}
###